services:
  build:
    build: .
    ports:
      - "1416:80"

  publish:
    build:
      context: .
      target: publish
    depends_on:
      - build

  docs:
    build:
      context: .
      target: docs
    depends_on:
      - build
    ports:
      - "1416:80"
